# -*- coding: utf-8 -*-
"""LAB7_PES1UG23AM309.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9P7ajTnqlZt2WH_VbXoDoy1BzYS6ktY

# Week 14: CNN Lab - Rock, Paper, Scissors

**Objective:** Build, train, and test a Convolutional Neural Network (CNN) to classify images of hands playing Rock, Paper, or Scissors.

### Step 1: Setup and Data Download

This first cell downloads the dataset from Kaggle.
"""

import kagglehub

path = kagglehub.dataset_download("drgfreeman/rockpaperscissors")

print("Path to dataset files:", path)

import shutil
import os

src_root = "/kaggle/input/rockpaperscissors"
dst_root = "/content/dataset"

os.makedirs(dst_root, exist_ok=True)

folders_to_copy = ["rock", "paper", "scissors"]

for folder in folders_to_copy:
    src_path = os.path.join(src_root, folder)
    dst_path = os.path.join(dst_root, folder)

    if os.path.exists(src_path):
        shutil.copytree(src_path, dst_path, dirs_exist_ok=True)
        print("Copied:", folder)
    else:
        print("Folder not found:", folder)

"""### Step 2: Imports and Device Setup

Import the necessary libraries and check if a GPU is available.
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split
from PIL import Image
import numpy as np

# TODO: Set the 'device' variable
# Check if CUDA (GPU) is available, otherwise use CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)

"""### Step 3: Data Loading and Preprocessing

Here we will define our image transformations, load the dataset, split it, and create DataLoaders.
"""

DATA_DIR = "/content/dataset"


# TODO: Define the image transforms
# We need to:
# 1. Resize all images to 128x128
# 2. Convert them to Tensors
# 3. Normalize them (mean=0.5, std=0.5)
transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])


# Load dataset using ImageFolder
full_dataset = datasets.ImageFolder(DATA_DIR, transform=transform)

class_names = full_dataset.classes
print("Classes:", class_names)

# TODO: Split the dataset
# We want 80% for training and 20% for testing
train_size = int(0.8 * len(full_dataset)) # <-- Calculate 80% of len(full_dataset)
test_size = len(full_dataset) - train_size  # <-- Calculate 20% (or the remainder)

# TODO: Use random_split to create train_dataset and test_dataset
train_dataset, test_dataset = random_split(full_dataset, [train_size, test_size]) # <-- Replace this


# TODO: Create the DataLoaders
# Use a batch_size of 32
# Shuffle the training loader, but not the test loader
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True) # <-- Replace this
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)  # <-- Replace this

print(f"Total images: {len(full_dataset)}")
print(f"Training images: {len(train_dataset)}")
print(f"Test images: {len(test_dataset)}")

"""### Step 4: Define the CNN Model

Fill in the `conv_block` and `fc_block` with the correct layers.
"""

class RPS_CNN(nn.Module):
    def __init__(self):
        super(RPS_CNN, self).__init__()

        # TODO: Define the convolutional block
        # We want 3 blocks:
        # 1. Conv2d(3 -> 16 channels, kernel=3, padding=1), ReLU, MaxPool2d(2)
        # 2. Conv2d(16 -> 32 channels, kernel=3, padding=1), ReLU, MaxPool2d(2)
        # 3. Conv2d(32 -> 64 channels, kernel=3, padding=1), ReLU, MaxPool2d(2)
        self.conv_block = nn.Sequential(
            nn.Conv2d(3, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)
        )

        # After 3 MaxPool(2) layers, our 128x128 image becomes:
        # 128 -> 64 -> 32 -> 16
        # So the flattened size is 64 * 16 * 16

        # TODO: Define the fully-connected (classifier) block
        # We want:
        # 1. Flatten the input
        # 2. Linear layer (64 * 16 * 16 -> 256)
        # 3. ReLU
        # 4. Dropout (p=0.3)
        # 5. Linear layer (256 -> 3) (3 classes: rock, paper, scissors)
        self.fc = nn.Sequential(
            nn.Flatten(),
            nn.Linear(64 * 16 * 16, 256),
            nn.ReLU(),
            nn.Dropout(p=0.3),
            nn.Linear(256, 3)
        )

    def forward(self, x):
        x = self.conv_block(x)
        x = self.fc(x)
        return x

# TODO: Initialize the model, criterion, and optimizer
# 1. Create an instance of RPS_CNN and move it to the 'device'
model = RPS_CNN().to(device) # <-- Replace this

# 2. Define the loss function (Criterion). Use CrossEntropyLoss for classification.
criterion = nn.CrossEntropyLoss() # <-- Replace this

# 3. Define the optimizer. Use Adam with a learning rate of 0.001
optimizer = optim.Adam(model.parameters(), lr=0.001) # <-- Replace this

print(model)

"""### Step 5: Train the Model

Fill in the core training steps inside the loop.
"""

EPOCHS = 10

for epoch in range(EPOCHS):
    model.train() # Set the model to training mode
    total_loss = 0

    for images, labels in train_loader:
        # Move data to the correct device
        images, labels = images.to(device), labels.to(device)

        # TODO: Implement the training steps
        # 1. Clear the gradients (optimizer.zero_grad())
        optimizer.zero_grad()

        # 2. Perform a forward pass (get model outputs)
        outputs = model(images)

        # 3. Calculate the loss (using criterion)
        loss = criterion(outputs, labels)

        # 4. Perform a backward pass (loss.backward())
        loss.backward()

        # 5. Update the weights (optimizer.step())
        optimizer.step()


        total_loss += loss.item()

    print(f"Epoch {epoch+1}/{EPOCHS}, Loss = {total_loss/len(train_loader):.4f}")

print("Training complete!")

"""### Step 6: Evaluate the Model

Test the model's accuracy on the unseen test set.
"""

model.eval() # Set the model to evaluation mode
correct = 0
total = 0

# TODO: Use torch.no_grad()
# We don't need to calculate gradients during evaluation
with torch.no_grad(): # <-- Replace this
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)

        # TODO: Get model predictions
        # 1. Get the raw model outputs (logits)
        outputs = model(images) # <-- Replace this

        # 2. Get the predicted class (the one with the highest score)
        #    Hint: use torch.max(outputs, 1)
        _, predicted = torch.max(outputs.data, 1) # <-- Replace this

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"Test Accuracy: {100 * correct / total:.2f}%")

"""### Step 7: Test on a Single Image

Let's see how the model performs on one image.
"""

def predict_image(model, img_path):
    model.eval()

    img = Image.open(img_path).convert("RGB")
    # Apply the same transforms as training, and add a batch dimension (unsqueeze)
    img = transform(img).unsqueeze(0).to(device)

    with torch.no_grad():
        # TODO: Get the model prediction
        # 1. Get the raw model outputs (logits)
        output = model(img) # <-- Replace this

        # 2. Get the predicted class index
        _, pred = torch.max(output.data, 1) # <-- Replace this

    return class_names[pred.item()]

# Test the function (this path should exist)
test_img_path = "/content/dataset/paper/0Uomd0HvOB33m47I.png"
prediction = predict_image(model, test_img_path)
print(f"Model prediction for {test_img_path}: {prediction}")

"""### Step 8: Play the Game!

This code is complete. If your model is trained, you can run this cell to have the model play against itself.
"""

import random
import os

def pick_random_image(class_name):
    folder = f"/content/dataset/{class_name}"
    files = os.listdir(folder)
    img = random.choice(files)
    return os.path.join(folder, img)

def rps_winner(move1, move2):
    if move1 == move2:
        return "Draw"

    rules = {
        "rock": "scissors",
        "paper": "rock",
        "scissors": "paper"
    }

    if rules[move1] == move2:
        return f"Player 1 wins! {move1} beats {move2}"
    else:
        return f"Player 2 wins! {move2} beats {move1}"


# -----------------------------------------------------------
# 1. Choose any two random classes
# -----------------------------------------------------------

choices = ["rock", "paper", "scissors"]
c1 = random.choice(choices)
c2 = random.choice(choices)

img1_path = pick_random_image(c1)
img2_path = pick_random_image(c2)

print("Randomly selected images:")
print("Image 1:", img1_path)
print("Image 2:", img2_path)


# -----------------------------------------------------------
# 2. Predict their labels using the model
# -----------------------------------------------------------

p1 = predict_image(model, img1_path)
p2 = predict_image(model, img2_path)

print("\nPlayer 1 shows:", p1)
print("Player 2 shows:", p2)

# -----------------------------------------------------------
# 3. Decide the winner
# -----------------------------------------------------------

print("\nRESULT:", rps_winner(p1, p2))